--- #YAML:1.0
name:                 VCS-Lite-Repository
version:              0.11
abstract:             A minimal version control system - the repository
author:
  - Barbie <barbie@cpan.org>

license:              artistic_2
distribution_type:    module
installdirs:          site

requires:
  perl:                     5.006
  Params::Validate:         0
  Time::Piece:              0
  VCS::Lite:                0.05
  YAML:                     0
recommends:
  Test::CPAN::Meta:         0
  Test::CPAN::Meta::JSON:   0
  Test::Pod:                1.00
  Test::Pod::Coverage:      0.08
build_requires:
  IO::File:                 0
  Test::More:               0.70

provides:
  VCS::Lite::Common:
    file:     lib/VCS/Lite/Common.pm
    version:  0.11
  VCS::Lite::Element:
    file:     lib/VCS/Lite/Element.pm
    version:  0.11
  VCS::Lite::Element::Binary:
    file:     lib/VCS/Lite/Element/Binary.pm
    version:  0.11
  VCS::Lite::Repository:
    file:     lib/VCS/Lite/Repository.pm
    version:  0.11
  VCS::Lite::Shell:
    file:     lib/VCS/Lite/Shell.pm
    version:  0.11
  VCS::Lite::Store:
    file:     lib/VCS/Lite/Store.pm
    version:  0.11
  VCS::Lite::Store::Storable:
    file:     lib/VCS/Lite/Store/Storable.pm
    version:  0.11
  VCS::Lite::Store::YAML:
    file:     lib/VCS/Lite/Store/YAML.pm
    version:  0.11
no_index:
  directory:
    - t
    - examples

meta-spec:
   version:   1.4
   url:       http://module-build.sourceforge.net/META-spec-v1.4.html
generated_by: Barbie's Brain 1.0
