# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         VCS-Lite-Repository
version:      0.06
version_from: lib/VCS/Lite/Repository.pm
installdirs:  site
requires:
    Params::Validate:              0
    Test::More:                    0
    Time::Piece:                   0
    VCS::Lite:                     0.05
    YAML:                          0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.21
